"""Schnorr sigma protocol and Fiat-Shamir compilation for Chapter 33.

The protocol proves knowledge of a witness x in Z_n \\ {0} such that
``h = g^x mod p`` for public ``(g, h)`` in the multiplicative group
F_p^*. The same toy group Chapter 32's ``toy_kzg`` module uses is
reused here: a safe-prime ``p = 2027 = 2 * 1013 + 1`` with prime-order
subgroup ``n = 1013`` generated by ``g = 4``. Chapter 33 writes the
subgroup order ``n`` and reserves ``q`` for the adversary's query
budget, which is what ``q`` means in the sibling
``measure_and_reprogram`` module; this module follows that convention.

Three-move interactive Schnorr:

1. Prover picks nonce ``r`` uniformly in Z_n \\ {0}, sends
   ``a = g^r mod p``.
2. Verifier sends challenge ``e`` uniformly in Z_n.
3. Prover sends ``z = (r + e * x) mod n``.

Verifier accepts if ``g^z == a * h^e mod p``.

Fiat-Shamir compilation: replace the verifier's challenge with a
random oracle query at a transcript hash. The prover computes
``e = RO(pk || a)`` in place of receiving ``e`` from the verifier,
then sends the proof ``(a, z)``. The verifier recomputes the same
oracle query, derives ``e``, and runs the Schnorr verification
equation.

The classical Fiat-Shamir proof of soundness uses rewinding: extract
two accepting transcripts at the same commitment ``a`` but different
challenges, solve a 2x2 linear system in Z_n, recover x. The QROM
obstruction is that rewinding is incompatible with superposition
queries; Chapter 33's prose develops that argument, and the measure-
and-reprogram scaffolding in the sibling module illustrates the
classical side of the reduction that replaces rewinding.
"""

from __future__ import annotations

import secrets
from dataclasses import dataclass

from .rom_simulator import RandomOracle


DEFAULT_PRIME = 2027
DEFAULT_ORDER = 1013
DEFAULT_GENERATOR = 4


@dataclass
class SchnorrKeypair:
    """Schnorr witness and public key.

    ``sk`` is the witness ``x`` in ``[1, n - 1]``. ``pk`` is
    ``h = g^x mod p``. The keypair is produced by ``keygen``.
    """

    sk: int
    pk: int


@dataclass
class InteractiveTranscript:
    """Three-move interactive Schnorr transcript.

    Fields ``commitment``, ``challenge``, ``response`` correspond to
    Schnorr's ``(a, e, z)`` triple. Element ``a`` lives in F_p^*;
    ``e`` and ``z`` live in Z_n.
    """

    commitment: int
    challenge: int
    response: int


@dataclass
class FiatShamirProof:
    """Non-interactive Fiat-Shamir-compiled Schnorr proof ``(a, z)``.

    The verifier recomputes the challenge by querying the random oracle
    at the serialized transcript prefix ``pk || a``.
    """

    commitment: int
    response: int


def keygen(sk: int | None = None) -> SchnorrKeypair:
    """Generate a Schnorr keypair in the toy group.

    If ``sk`` is None, a fresh witness is sampled uniformly in
    ``[1, n - 1]`` via ``secrets.randbelow``. A deterministic ``sk``
    may be passed for reproducibility in tests.
    """
    # EXERCISE: implement this function.
    #
    # With sk supplied, check it lies in [1, n - 1] and reject anything
    # else; the witness x = 0 is excluded because it forces the public key h
    # = 1 and trivializes the relation. With sk None, draw one uniformly
    # from that range as 1 + secrets.randbelow(n - 1). The public key is h =
    # g^x mod p in the toy group carried over from Ch 32's toy_kzg: p = 2027
    # = 2 * 1013 + 1, subgroup order n = 1013, generator g = 4.
    #
    # Reference: Chapter 33, 'A Schnorr proof compiled three ways'
    #
    # Proved by:
    #   tests/ch33/test_fiat_shamir_schnorr.py
    raise NotImplementedError("exercise: keygen")


def interactive_prove(
    keypair: SchnorrKeypair,
    challenge: int,
    nonce: int | None = None,
) -> InteractiveTranscript:
    """Run the Schnorr prover's first and third moves against a given
    challenge.

    The verifier's challenge ``e`` is passed in directly. The per-proof
    nonce ``r`` is either given (for deterministic tests) or sampled
    uniformly in ``[1, n - 1]``. Returns the full ``(a, e, z)``
    transcript.
    """
    # EXERCISE: implement this function.
    #
    # Schnorr's first and third moves, with the verifier's challenge handed
    # in rather than derived. Commit to a = g^r mod p for a nonce r, sampled
    # uniformly in [1, q - 1] when none is given, and answer z = (r + e * x)
    # mod q. The commitment lives in F_p^* and the response in F_q; reducing
    # the response modulo p, or the commitment modulo q, is the usual way to
    # get this wrong. Reject a challenge outside [0, q - 1] and a nonce
    # outside [1, q - 1].
    #
    # Reference: Chapter 33, 'A Schnorr proof compiled three ways' (Block 1)
    #
    # Proved by:
    #   tests/ch33/test_fiat_shamir_schnorr.py
    raise NotImplementedError("exercise: interactive_prove")


def interactive_verify(pk: int, transcript: InteractiveTranscript) -> bool:
    """Verify a three-move Schnorr transcript.

    Returns True iff ``g^z == a * h^e mod p``, with ``(a, e, z)``
    drawn from the transcript.
    """
    if pk < 1 or pk >= DEFAULT_PRIME:
        raise ValueError("pk must lie in [1, p - 1]")
    lhs = pow(DEFAULT_GENERATOR, transcript.response, DEFAULT_PRIME)
    rhs = (
        transcript.commitment
        * pow(pk, transcript.challenge, DEFAULT_PRIME)
    ) % DEFAULT_PRIME
    return lhs == rhs


def _transcript_bytes(pk: int, commitment: int) -> bytes:
    """Serialize ``(pk, commitment)`` for the Fiat-Shamir oracle query.

    Both elements live in ``[0, p - 1]`` so two-byte encoding suffices
    (``p = 2027 < 2^11``); we use four bytes per element for a clear
    delimiter.
    """
    if pk < 0 or pk >= DEFAULT_PRIME:
        raise ValueError("pk must lie in [0, p - 1]")
    if commitment < 0 or commitment >= DEFAULT_PRIME:
        raise ValueError("commitment must lie in [0, p - 1]")
    return pk.to_bytes(4, "big") + commitment.to_bytes(4, "big")


def fs_prove(
    keypair: SchnorrKeypair,
    oracle: RandomOracle,
    nonce: int | None = None,
) -> FiatShamirProof:
    """Produce a Fiat-Shamir-compiled Schnorr proof.

    The oracle's ``output_modulus`` must equal ``DEFAULT_ORDER`` so that
    the oracle's response lies in the Schnorr challenge space Z_n. The
    challenge ``e`` is computed as ``oracle.query(pk || a)``. The proof
    is the pair ``(a, z)``; the verifier recomputes ``e`` by querying
    the same oracle at the same serialized input.
    """
    # EXERCISE: implement this function.
    #
    # The same prover with the verifier deleted. Compute a = g^r, then
    # derive the challenge yourself as oracle.query on the serialized
    # transcript prefix pk || a instead of waiting to receive it, and answer
    # z = (r + e * x) mod q. The proof carries only (a, z); e is
    # reconstructable from the transcript by anyone holding the oracle.
    # Require the oracle's output_modulus to equal q, so its response is
    # already a legal element of the challenge space, and reject a nonce
    # outside [1, q - 1].
    #
    # Reference: Chapter 33, 'Three-move sigma with Fiat-Shamir' (Block 2)
    #
    # Proved by:
    #   tests/ch33/test_fiat_shamir_schnorr.py
    raise NotImplementedError("exercise: fs_prove")


def fs_verify(pk: int, proof: FiatShamirProof, oracle: RandomOracle) -> bool:
    """Verify a Fiat-Shamir-compiled Schnorr proof against an oracle.

    Recomputes the challenge ``e = oracle.query(pk || a)`` and returns
    True iff ``g^z == a * h^e mod p``. The verifier uses the same oracle
    instance the prover queried, so subsequent verification calls hit
    the cache.
    """
    # EXERCISE: implement this function.
    #
    # Recompute e by querying the oracle at the same serialized prefix built
    # from pk and the proof's own commitment, then check g^z == a * h^e mod
    # p. Determinism is the whole point of the compilation: any verifier
    # holding the same oracle derives the same challenge, so no interaction
    # is needed and a fresh oracle with the same seed accepts the same
    # proof. Require the oracle's output_modulus to equal q and reject a pk
    # outside [1, p - 1].
    #
    # Reference: Chapter 33, 'Three-move sigma with Fiat-Shamir' (Block 2)
    #
    # Proved by:
    #   tests/ch33/test_fiat_shamir_schnorr.py
    raise NotImplementedError("exercise: fs_verify")


def rewind_extract(
    pk: int,
    transcript_a: InteractiveTranscript,
    transcript_b: InteractiveTranscript,
) -> int:
    """Extract the Schnorr witness from two accepting transcripts.

    Both transcripts must share the same commitment ``a`` and have
    distinct challenges ``e_a != e_b``. The witness is recovered as
    ``x = (z_a - z_b) * (e_a - e_b)^{-1} mod n``.

    This is the classical rewinding extractor. It is the step the QROM
    reduction cannot directly replicate: rewinding requires observing
    the adversary's queries at each branch, which collapses a quantum
    superposition. Measure-and-reprogram (Chapter 33 prose) is the
    replacement technique.
    """
    # EXERCISE: implement this function.
    #
    # Two accepting transcripts that share a commitment but differ in
    # challenge yield the witness: x = (z_a - z_b) * (e_a - e_b)^{-1} mod q.
    # Take both differences modulo q and invert the challenge difference
    # with pow(delta_e, -1, q), which exists because q is prime and the
    # challenges differ. Refuse mismatched commitments, equal challenges,
    # and either transcript failing interactive_verify. This is the
    # classical rewinding extractor, and it is exactly the step the QROM
    # cannot replay: observing the adversary's queries on each branch
    # requires a measurement, the measurement collapses the superposition,
    # and there is no state left to rewind to.
    #
    # Reference: Chapter 33, 'A Schnorr proof compiled three ways' and Exercise E3
    #
    # Proved by:
    #   tests/ch33/test_fiat_shamir_schnorr.py
    raise NotImplementedError("exercise: rewind_extract")
