"""Low-degree extension (Reed-Solomon encoding) for Chapter 34.

The trace polynomial interpolated on the trace domain is evaluated on a
larger LDE domain to produce a Reed-Solomon codeword. FRI then proves
the codeword is close to a low-degree polynomial, which is the L2
commitment to the trace polynomial under the four-layer decomposition.

The LDE domain is a coset of the order-32 subgroup of F_97^*. Choosing
a coset (rather than the subgroup itself) keeps the LDE domain disjoint
from the trace domain, which avoids zero values of the trace-domain
vanishing polynomial at LDE points. The toy uses:

- Trace domain: <64>, the order-8 subgroup (generator 64 = 28^4).
- LDE base subgroup: <28>, the order-32 subgroup.
- LDE domain: h * <28> where h = 5, the primitive root.

Because ``5`` is outside the order-32 subgroup (5 has order 96), the
coset is disjoint from the subgroup and therefore from the trace
domain. The coset is closed under negation because -1 = 28^16 is inside
the order-32 subgroup, so the coset's negation is itself.
"""

from __future__ import annotations

from .arithmetization import DEFAULT_PRIME, TRACE_DOMAIN_GENERATOR, TRACE_LENGTH


# LDE parameters over F_97.
LDE_BLOWUP = 4
LDE_SIZE = TRACE_LENGTH * LDE_BLOWUP  # 32
# 28 has order 32 in F_97* (derived from primitive root 5 via
# 5^(96/32) = 5^3 = 125 mod 97 = 28).
LDE_GENERATOR = 28
# Coset shifter. 5 is a primitive root of F_97*, so it is not in the
# order-32 subgroup generated by 28, which guarantees the coset is
# disjoint from the subgroup.
COSET_SHIFT = 5


def mod_inv(a: int, prime: int) -> int:
    """Modular inverse via Fermat's little theorem (prime modulus)."""
    # EXERCISE: implement this function.
    #
    # Return the inverse of a modulo prime. pow(a, -1, prime) computes it;
    # on a prime modulus that is Fermat's little theorem, a^(prime - 2) mod
    # prime. Raise ValueError when a is zero modulo prime rather than
    # letting pow raise its own error, so the package keeps one error
    # contract. Every FRI fold inverts 2 and the domain point x through this
    # routine, so it is the inner loop of the fold rather than a utility.
    #
    # Reference: Chapter 34, '4.3 FRI with Fiat-Shamir challenges' (Block 4)
    #
    # Proved by:
    #   tests/ch34/test_lde.py
    #   tests/ch34/test_fri_full.py
    raise NotImplementedError("exercise: mod_inv")


def eval_poly(coeffs: list[int], x: int, prime: int) -> int:
    """Horner-rule polynomial evaluation modulo ``prime``.

    Raises ValueError on an empty coefficient list to keep the error
    contract consistent with the rest of the package.
    """
    if not coeffs:
        raise ValueError("coefficient list must be non-empty")
    result = 0
    for c in reversed(coeffs):
        result = (result * x + c) % prime
    return result


def trace_domain(
    generator: int = TRACE_DOMAIN_GENERATOR,
    length: int = TRACE_LENGTH,
    prime: int = DEFAULT_PRIME,
) -> list[int]:
    """Return the trace domain as a list of length ``length``.

    The domain is ``{generator^i : i = 0..length-1}``. The generator
    must have order exactly ``length``. Raises ValueError if the
    generator is invalid.
    """
    # EXERCISE: implement this function.
    #
    # The trace domain is {generator^i : i = 0..length-1}. Carry a running
    # power from 1, appending it before each multiplication, and after the
    # last step check the accumulator is back at 1: if it is not, the
    # generator's order is not length and the list is not the subgroup it
    # claims to be. Reject a length that is not a power of two above one,
    # and a prime below two. For the running example the generator is g_8 =
    # 64, which is 5^12 mod 97.
    #
    # Reference: Chapter 34, 'AIR, LDE, and the Reed-Solomon lift' and '4.2 LDE' (Block 3)
    #
    # Proved by:
    #   tests/ch34/test_lde.py
    raise NotImplementedError("exercise: trace_domain")


def lde_domain(
    size: int = LDE_SIZE,
    generator: int = LDE_GENERATOR,
    coset_shift: int = COSET_SHIFT,
    prime: int = DEFAULT_PRIME,
) -> list[int]:
    """Return an LDE domain of size ``size`` as a coset of ``<generator>``.

    The domain is ``{coset_shift * generator^i : i = 0..size-1}``. The
    generator must have order exactly ``size``. Raises ValueError on
    non-power-of-two sizes, on an invalid generator, or on a coset
    shifter that lies inside ``<generator>`` (which would make the
    coset the subgroup itself rather than a disjoint coset).
    """
    # EXERCISE: implement this function.
    #
    # Build the order-size subgroup as powers of generator exactly as
    # trace_domain does, closing order check included, then multiply every
    # element by coset_shift. The shift is what keeps the LDE domain
    # disjoint from the trace domain, so the trace-domain vanishing
    # polynomial is nonzero at every LDE point; refuse a shift that already
    # lies inside the subgroup, because the coset would then be the subgroup
    # itself. Reject a shift that is zero modulo prime and a size that is
    # not a power of two above one. Negation-closure survives the shift
    # because -1 = g_32^16 sits inside the order-32 subgroup, and
    # negation-closure is the only structure FRI folding needs from this
    # domain.
    #
    # Reference: Chapter 34, 'Eight Fibonacci steps, one non-interactive proof' and '4.2 LDE' (Block 3)
    #
    # Proved by:
    #   tests/ch34/test_lde.py
    raise NotImplementedError("exercise: lde_domain")


def extend_polynomial(
    coeffs: list[int],
    domain: list[int],
    prime: int = DEFAULT_PRIME,
) -> list[int]:
    """Evaluate a polynomial on ``domain`` to produce its Reed-Solomon codeword.

    Raises ValueError for an empty coefficient list or an empty domain.
    """
    # EXERCISE: implement this function.
    #
    # The Reed-Solomon encoding step: evaluate the polynomial at every point
    # of the domain and return the codeword in domain order. A length-L
    # trace becomes a length-N codeword, and any L of the N values
    # reconstruct the polynomial. That redundancy is not a cryptographic
    # step in itself; it is what FRI later exploits, because a codeword
    # close to a low-degree polynomial passes proximity testing and one far
    # from every such polynomial fails. Raise ValueError for an empty
    # coefficient list or an empty domain.
    #
    # Reference: Chapter 34, 'AIR, LDE, and the Reed-Solomon lift' and '4.2 LDE' (Block 3)
    #
    # Proved by:
    #   tests/ch34/test_lde.py
    raise NotImplementedError("exercise: extend_polynomial")


def vanishing_polynomial(
    trace_pts: list[int],
    x: int,
    prime: int = DEFAULT_PRIME,
) -> int:
    """Evaluate the trace-domain vanishing polynomial at ``x``.

    Z_T(x) = prod_{w in trace_pts}(x - w) mod prime. Zero if x lies in
    trace_pts, nonzero otherwise. Raises ValueError on empty
    ``trace_pts``.
    """
    # EXERCISE: implement this function.
    #
    # Z_T(x) is the product over w in trace_pts of (x - w), reduced modulo
    # prime. It is zero exactly on the trace domain and nonzero everywhere
    # else, which is what the coset construction of the LDE domain buys at
    # every LDE point. Reduce each factor before multiplying so a negative
    # difference does not leak through. Raise ValueError on empty trace_pts.
    # The simplified pipeline never divides by Z_T, but the disjointness it
    # certifies is load-bearing for any extension that adds a composition
    # polynomial.
    #
    # Reference: Chapter 34, '4.2 LDE'
    #
    # Proved by:
    #   tests/ch34/test_lde.py
    raise NotImplementedError("exercise: vanishing_polynomial")
