"""The 2D lattice Chapter 3 draws, and the membership test that closes it.

Chapter 3 opens on the lattice `L` generated by `b1 = (2, 7)` and `b2 = (5, 3)`,
and *proves* that its shortest nonzero vector has norm 5 rather than merely
exhibiting one of that length. The proof is a finite enumeration, and this module
is that enumeration plus the membership test that makes it finite.

The membership test is the part worth reading. A point `(x, y)` lies in `L`
exactly when `b12 * x - b11 * y` is divisible by `abs(det B)`, which for the
chapter's basis is `7x - 2y == 0 (mod 29)`. That is derived rather than guessed.
Writing `x = a*b11 + b*b21` and `y = a*b12 + b*b22` and eliminating `a` leaves

    b12 * x - b11 * y == -b * det B

so divisibility is *necessary*. It is also *sufficient*, which is what lets the
test stand in for solving the system: `gcd(b12, b11) == 1` for this basis, so the
form is onto `Z / abs(det)`, its kernel therefore has index `abs(det)` in `Z^2`,
and `L` has that same index, so the kernel and `L` coincide. Chapter 7 develops
what a basis means over `Z`; nothing here needs more than the derivation above.

Standard library only.
"""

from __future__ import annotations

Basis = tuple[tuple[int, int], tuple[int, int]]
Point = tuple[int, int]

#: The basis Chapter 3 draws, as rows, matching the exercise's matrix B.
CHAPTER_BASIS: Basis = ((2, 7), (5, 3))


def determinant(basis: Basis) -> int:
    """The determinant of a 2x2 basis given as rows. Signed, not absolute."""
    (b11, b12), (b21, b22) = basis
    return b11 * b22 - b12 * b21


def in_lattice(basis: Basis, point: Point) -> bool:
    """Whether `point` lies in the lattice generated by `basis`.

    Uses the membership congruence derived in the module docstring, which is why
    this is a single modulo rather than a search over coefficients.
    """
    # EXERCISE: implement this function.
    #
    # One modulo, not a search. Write x = a*b11 + b*b21 and y = a*b12 +
    # b*b22, then eliminate a by multiplying the first equation by b12 and
    # the second by b11 and subtracting: what is left is b12*x - b11*y == -b
    # * det B. So the point is in the lattice exactly when b12*x - b11*y is
    # divisible by abs(det B). For the chapter's basis that is 7x - 2y == 0
    # (mod 29), and the 29 is abs(det B) rather than a coincidence. Do not
    # validate the input.
    #
    # Reference: Chapter 3, 'A lattice you can draw'
    #
    # Proved by:
    #   tests/ch03/test_lattice.py
    raise NotImplementedError("exercise: in_lattice")


def enumerate_coefficient_box(
    basis: Basis, bound: int
) -> list[tuple[int, Point, Point]]:
    """Every nonzero combination with coefficients in `[-bound, bound]`.

    Returns `(squared_norm, (a, b), (x, y))` triples sorted by squared norm, so
    the first entry is the shortest vector *inside the box*. That qualifier is
    the point of the exercise: a box search bounds the minimum from above and
    proves nothing about vectors outside it.
    """
    # EXERCISE: implement this function.
    #
    # Two nested loops over the coefficients from -bound to bound, skipping
    # (0, 0), building the vector a*b1 + b*b2 and its squared norm. Return
    # (squared_norm, (a, b), (x, y)) triples sorted, so the caller reads the
    # shortest entry first. Keep the squared norm rather than the norm: it
    # stays an integer, so comparisons are exact and there is nothing to
    # round. This search bounds the minimum from above and proves nothing
    # about vectors outside the box, which is the distinction exercise 1
    # turns on.
    #
    # Reference: Chapter 3, exercise 1
    #
    # Proved by:
    #   tests/ch03/test_lattice.py
    raise NotImplementedError("exercise: enumerate_coefficient_box")


def lattice_points_up_to(basis: Basis, max_squared_norm: int) -> list[Point]:
    """Every lattice point with squared norm at most `max_squared_norm`.

    Enumerates the integer points in the bounding square and keeps the ones the
    membership congruence accepts. The origin is included, because it is a
    lattice point; callers wanting nonzero vectors filter it out.

    This is the direction that makes the chapter's argument a proof: it is
    complete over the region, so an empty result really means no such vector
    exists rather than none was found.
    """
    # EXERCISE: implement this function.
    #
    # The direction that makes the chapter's argument a proof rather than a
    # search. Walk every integer point in the bounding square, keep the ones
    # within the squared-norm limit that in_lattice accepts, and include the
    # origin. Because it is complete over the region, an empty result means
    # no such vector exists. Take care computing the bound from the squared
    # norm: int(n ** 0.5) can fall one short on a perfect square through
    # float rounding, so step it up while (limit + 1) ** 2 still fits.
    #
    # Reference: Chapter 3, 'A lattice you can draw'
    #
    # Proved by:
    #   tests/ch03/test_lattice.py
    raise NotImplementedError("exercise: lattice_points_up_to")


def shortest_vectors(basis: Basis) -> tuple[int, list[Point]]:
    """The squared norm of the shortest nonzero vector, and every attaining one.

    Searches outward by squared norm and stops at the first radius that contains
    a nonzero lattice point, so the answer is exact rather than a best-so-far.
    A lattice is closed under negation, so the attaining set always comes in
    plus-minus pairs and never has just one element.
    """
    # EXERCISE: implement this function.
    #
    # Grow the radius until a nonzero lattice point appears, then return
    # that squared norm together with every point attaining it. Stopping at
    # the first radius that contains anything is what makes the answer exact
    # instead of best-so-far. Expect the attaining set to have even size: a
    # lattice is closed under negation, so a shortest vector always comes
    # with its negative.
    #
    # Reference: Chapter 3, 'A lattice you can draw'
    #
    # Proved by:
    #   tests/ch03/test_lattice.py
    raise NotImplementedError("exercise: shortest_vectors")
