"""Velu's formulas for computing isogenies E -> E/<P>.

Given an elliptic curve E: y^2 = x^3 + a*x + b over F_{p^2} and a
finite subgroup generated by a point P of known order, compute:
  - the image of any point Q under the isogeny
  - the coefficients (a', b') of the codomain curve E/<P>

Point evaluation uses the formula from Galbraith (Mathematics of
Public Key Cryptography, Section 25.1.1):

  x(phi(Q)) = x(Q) + sum_{R in S*} [x(Q + R) - x(R)]
  y(phi(Q)) = y(Q) + sum_{R in S*} [y(Q + R) - y(R)]

where S* = S \\ {O} is the kernel minus the identity.  This requires
only point addition on the source curve.
"""

from __future__ import annotations

from isogenies.fp2 import (
    fp2_add,
    fp2_eq,
    fp2_inv,
    fp2_mul,
    fp2_sqr,
    fp2_sub,
    fp2_zero,
)
from isogenies.curve import Fp2, Point, point_add, scalar_mul


def compute_kernel(
    gen: Point, order: int, a: Fp2, p: int
) -> list[Point]:
    """Enumerate all points in <gen>: {O, gen, 2*gen, ..., (order-1)*gen}."""
    pts: list[Point] = [None]
    current = gen
    for _ in range(1, order):
        pts.append(current)
        current = point_add(current, gen, a, p)
    return pts


def velu_eval(
    Q: Point, kernel: list[Point], a: Fp2, p: int
) -> Point:
    """Evaluate the isogeny at a point Q.

    Returns None (point at infinity) if Q is in the same coset as a
    kernel element, i.e., if Q itself is in the kernel or if Q + R = O
    for some kernel point R.
    """
    if Q is None:
        return None

    x_Q, y_Q = Q
    x_new = x_Q
    y_new = y_Q

    for R in kernel:
        if R is None:
            continue
        x_R, y_R = R

        # If Q shares an x-coordinate with a kernel point, phi(Q) = O.
        if fp2_eq(x_Q, x_R, p):
            return None

        QpR = point_add(Q, R, a, p)
        if QpR is None:
            return None
        x_QR, y_QR = QpR
        x_new = fp2_add(x_new, fp2_sub(x_QR, x_R, p), p)
        y_new = fp2_add(y_new, fp2_sub(y_QR, y_R, p), p)

    return (x_new, y_new)


def _recover_codomain(
    img1: tuple[Fp2, Fp2],
    img2: tuple[Fp2, Fp2],
    p: int,
) -> tuple[Fp2, Fp2]:
    """Recover (a', b') from two points on the codomain curve.

    Given (x1, y1) and (x2, y2) on y^2 = x^3 + a'x + b':
      a' = (y1^2 - x1^3 - y2^2 + x2^3) / (x1 - x2)
      b' = y1^2 - x1^3 - a'*x1
    """
    x1, y1 = img1
    x2, y2 = img2
    num = fp2_sub(
        fp2_sub(fp2_sqr(y1, p), fp2_mul(fp2_sqr(x1, p), x1, p), p),
        fp2_sub(fp2_sqr(y2, p), fp2_mul(fp2_sqr(x2, p), x2, p), p),
        p,
    )
    den = fp2_sub(x1, x2, p)
    a_new = fp2_mul(num, fp2_inv(den, p), p)
    b_new = fp2_sub(
        fp2_sub(fp2_sqr(y1, p), fp2_mul(fp2_sqr(x1, p), x1, p), p),
        fp2_mul(a_new, x1, p),
        p,
    )
    return a_new, b_new


def velu_isogeny(
    gen: Point, order: int, a: Fp2, b: Fp2, p: int,
    aux_points: list[Point] | None = None,
) -> tuple[Fp2, Fp2, list[Point], list[Point]]:
    """Compute the isogeny E -> E/<gen> and push auxiliary points through.

    Returns (a', b', kernel, aux_images) where aux_images[i] is the
    image of aux_points[i] under the isogeny.

    The codomain coefficients a', b' are recovered from two image
    points on the target curve.
    """
    # EXERCISE: implement this function.
    #
    # Build the kernel with compute_kernel, push every auxiliary point
    # through with velu_eval, and then recover the codomain from two of the
    # images. Collect only images that are not None and whose x-coordinates
    # differ from each other. When the auxiliary points do not supply two
    # such images, probe the source curve: walk x = 2, 3, ... as elements
    # (x, 0), solve y^2 = x^3 + a*x + b with fp2_sqrt, and push any point
    # found through the isogeny until two usable images exist. Raise
    # RuntimeError rather than recovering a curve from a single point.
    # Return (a', b', kernel, aux_images) with aux_images aligned index for
    # index with aux_points, None entries included, because the chain walk
    # reads the pushed kernel generator out of position 0.
    #
    # Reference: Chapter 22, 'Velu's formulas over F_p^2'
    #
    # Proved by:
    #   tests/ch22/test_velu.py
    #   tests/ch22/test_isogeny_graph.py
    raise NotImplementedError("exercise: velu_isogeny")
