"""Velu's formulas for computing isogenies E -> E/<P>.

Given an elliptic curve E: y^2 = x^3 + a*x + b over F_{p^2} and a
finite subgroup generated by a point P of known order, compute:
  - the image of any point Q under the isogeny
  - the coefficients (a', b') of the codomain curve E/<P>

Point evaluation uses the formula from Galbraith (Mathematics of
Public Key Cryptography, Section 25.1.1):

  x(phi(Q)) = x(Q) + sum_{R in S*} [x(Q + R) - x(R)]
  y(phi(Q)) = y(Q) + sum_{R in S*} [y(Q + R) - y(R)]

where S* = S \\ {O} is the kernel minus the identity.  This requires
only point addition on the source curve.
"""

from __future__ import annotations

from isogenies.fp2 import (
    fp2_add,
    fp2_eq,
    fp2_inv,
    fp2_mul,
    fp2_sqr,
    fp2_sub,
    fp2_zero,
)
from isogenies.curve import Fp2, Point, point_add, scalar_mul


def compute_kernel(
    gen: Point, order: int, a: Fp2, p: int
) -> list[Point]:
    """Enumerate all points in <gen>: {O, gen, 2*gen, ..., (order-1)*gen}."""
    pts: list[Point] = [None]
    current = gen
    for _ in range(1, order):
        pts.append(current)
        current = point_add(current, gen, a, p)
    return pts


def velu_eval(
    Q: Point, kernel: list[Point], a: Fp2, p: int
) -> Point:
    """Evaluate the isogeny at a point Q.

    Returns None (point at infinity) if Q is in the same coset as a
    kernel element, i.e., if Q itself is in the kernel or if Q + R = O
    for some kernel point R.
    """
    if Q is None:
        return None

    x_Q, y_Q = Q
    x_new = x_Q
    y_new = y_Q

    for R in kernel:
        if R is None:
            continue
        x_R, y_R = R

        # If Q shares an x-coordinate with a kernel point, phi(Q) = O.
        if fp2_eq(x_Q, x_R, p):
            return None

        QpR = point_add(Q, R, a, p)
        if QpR is None:
            return None
        x_QR, y_QR = QpR
        x_new = fp2_add(x_new, fp2_sub(x_QR, x_R, p), p)
        y_new = fp2_add(y_new, fp2_sub(y_QR, y_R, p), p)

    return (x_new, y_new)


def _recover_codomain(
    img1: tuple[Fp2, Fp2],
    img2: tuple[Fp2, Fp2],
    p: int,
) -> tuple[Fp2, Fp2]:
    """Recover (a', b') from two points on the codomain curve.

    Given (x1, y1) and (x2, y2) on y^2 = x^3 + a'x + b':
      a' = (y1^2 - x1^3 - y2^2 + x2^3) / (x1 - x2)
      b' = y1^2 - x1^3 - a'*x1
    """
    x1, y1 = img1
    x2, y2 = img2
    num = fp2_sub(
        fp2_sub(fp2_sqr(y1, p), fp2_mul(fp2_sqr(x1, p), x1, p), p),
        fp2_sub(fp2_sqr(y2, p), fp2_mul(fp2_sqr(x2, p), x2, p), p),
        p,
    )
    den = fp2_sub(x1, x2, p)
    a_new = fp2_mul(num, fp2_inv(den, p), p)
    b_new = fp2_sub(
        fp2_sub(fp2_sqr(y1, p), fp2_mul(fp2_sqr(x1, p), x1, p), p),
        fp2_mul(a_new, x1, p),
        p,
    )
    return a_new, b_new


def velu_isogeny(
    gen: Point, order: int, a: Fp2, b: Fp2, p: int,
    aux_points: list[Point] | None = None,
) -> tuple[Fp2, Fp2, list[Point], list[Point]]:
    """Compute the isogeny E -> E/<gen> and push auxiliary points through.

    Returns (a', b', kernel, aux_images) where aux_images[i] is the
    image of aux_points[i] under the isogeny.

    The codomain coefficients a', b' are recovered from two image
    points on the target curve.
    """
    kernel = compute_kernel(gen, order, a, p)
    if aux_points is None:
        aux_points = []

    # Evaluate the isogeny at all auxiliary points.
    aux_images = [velu_eval(pt, kernel, a, p) for pt in aux_points]

    # Recover codomain coefficients from two non-kernel image points.
    # First try auxiliary images; if not enough, search for probe points
    # on the source curve by trying F_p x-coordinates.
    codomain_pts: list[tuple[Fp2, Fp2]] = []
    for img in aux_images:
        if img is not None and len(codomain_pts) < 2:
            if not codomain_pts or not fp2_eq(img[0], codomain_pts[0][0], p):
                codomain_pts.append(img)

    if len(codomain_pts) < 2:
        # Probe with points on E(F_p): try x = 2, 3, 4, ...
        from isogenies.fp2 import fp2_sqrt
        for x_int in range(2, p):
            x_fp2 = (x_int, 0)
            x2 = fp2_sqr(x_fp2, p)
            x3 = fp2_mul(x2, x_fp2, p)
            rhs = fp2_add(fp2_add(x3, fp2_mul(a, x_fp2, p), p), b, p)
            y_fp2 = fp2_sqrt(rhs, p)
            if y_fp2 is None:
                continue
            probe = (x_fp2, y_fp2)
            img = velu_eval(probe, kernel, a, p)
            if img is None:
                continue
            if not codomain_pts or not fp2_eq(img[0], codomain_pts[0][0], p):
                codomain_pts.append(img)
                if len(codomain_pts) == 2:
                    break

    if len(codomain_pts) < 2:
        raise RuntimeError("could not find two non-kernel probe points")

    a_new, b_new = _recover_codomain(codomain_pts[0], codomain_pts[1], p)

    return a_new, b_new, kernel, aux_images
