"""Toy FRI commitment for Chapter 32.

Builds FRI (Fast Reed-Solomon Interactive Oracle Proof of Proximity)
as a commitment primitive over a small prime field. This module is
pedagogical, not production: Chapter 34 covers FRI-from-scratch at the
depth required to wrap it into a STARK. Ch 32's scope is FRI as a
polynomial commitment, demonstrating three things:

1. The folding structure: given f: L -> F, compute f': L^2 -> F of
   roughly half the domain size via f'(y) = (f(x) + f(-x))/2 +
   beta * (f(x) - f(-x))/(2x), where y = x^2 and beta is a verifier-
   supplied challenge.
2. The consistency check: after log_2(|L|) folds, the prover commits
   to a constant; the verifier queries consistency at random points
   along the folding chain.
3. The proximity-gap structure: a function far from low-degree passes
   the consistency check with negligible probability, bounded by the
   Ben-Sasson-Bentov-Horesh-Riabzev proximity argument
   (information-theoretic, unaffected by quantum adversaries on this
   side of the commitment; the quantum pressure on FRI-based SNARKs
   enters via the Merkle layer and the QROM compilation, not via the
   proximity gap itself).

The protocol below is interactive: the verifier sends challenges. A
Fiat-Shamir compilation belongs in Ch 33, and the full STARK pipeline
in Ch 34.
"""

from __future__ import annotations

from dataclasses import dataclass


# Default prime: 97 has p - 1 = 96 = 2^5 * 3. The 2^5 = 32 power-of-two
# subgroup is enough to demonstrate log_2(32) = 5 folding rounds. Fast
# to operate on.
DEFAULT_PRIME = 97


def mod_inv(a: int, prime: int) -> int:
    """Compute the multiplicative inverse of ``a`` modulo ``prime``."""
    if a % prime == 0:
        raise ValueError("no inverse for zero")
    return pow(a, -1, prime)


def eval_poly(coeffs: list[int], x: int, prime: int) -> int:
    """Horner-rule evaluation of a polynomial at ``x`` modulo prime."""
    result = 0
    for c in reversed(coeffs):
        result = (result * x + c) % prime
    return result


def generate_domain(size: int, generator: int, prime: int) -> list[int]:
    """Build a size-``size`` multiplicative subgroup coset.

    ``generator`` must have order at least ``size`` in F_prime^*. The
    resulting domain ``L`` is closed under negation when ``size`` is a
    power of two, which is the requirement for FRI folding to be
    well-defined. Raises ValueError for non-power-of-two sizes or
    when the generator has insufficient order.
    """
    if size < 2 or (size & (size - 1)) != 0:
        raise ValueError("size must be a power of two greater than one")
    domain: list[int] = []
    current = 1
    for _ in range(size):
        domain.append(current)
        current = (current * generator) % prime
    if current != 1:
        raise ValueError("generator order does not match domain size")
    return domain


@dataclass
class FRIFoldRound:
    """One round of the folding chain.

    ``evaluations`` is the function values f_i: L_i -> F. ``domain`` is
    L_i. ``beta`` is the verifier's challenge for this round (the
    challenge that produced ``evaluations`` from the prior round's
    oracle).
    """

    domain: list[int]
    evaluations: list[int]
    beta: int


def fold_once(
    evaluations: list[int],
    domain: list[int],
    beta: int,
    prime: int,
) -> tuple[list[int], list[int]]:
    """Apply one FRI folding round.

    For each pair ``(x, -x)`` in ``domain``, compute
    ``f'(x^2) = (f(x) + f(-x))/2 + beta * (f(x) - f(-x))/(2x)``, where
    beta is the verifier-supplied challenge. Returns the folded
    evaluations and the new domain ``{x^2 : x in first half of L}``.
    Requires the domain to be ordered so that index i+|L|/2 holds -L[i].
    """
    n = len(domain)
    if n != len(evaluations):
        raise ValueError("domain and evaluations must be the same length")
    if n < 2 or (n & (n - 1)) != 0:
        raise ValueError("domain size must be a power of two greater than one")

    half = n // 2
    # The subgroup generated by g of order n lays out as
    # g^0, g^1, ..., g^(n-1); the negation -g^i equals g^(i + n/2). So
    # the i-th pair is (domain[i], domain[i + half]) which are x and -x.
    new_domain: list[int] = []
    new_evals: list[int] = []
    two_inv = mod_inv(2, prime)
    for i in range(half):
        x = domain[i]
        fx = evaluations[i]
        f_neg_x = evaluations[i + half]
        even = ((fx + f_neg_x) * two_inv) % prime
        odd = ((fx - f_neg_x) * two_inv) % prime
        odd = (odd * mod_inv(x, prime)) % prime
        folded = (even + beta * odd) % prime
        new_evals.append(folded)
        new_domain.append((x * x) % prime)
    return new_evals, new_domain


def commit(
    coeffs: list[int],
    domain: list[int],
    prime: int = DEFAULT_PRIME,
) -> list[int]:
    """Produce the Reed-Solomon codeword over ``domain``.

    The FRI commitment to a polynomial is its evaluation vector on the
    public domain. The prover subsequently commits to this vector (in
    production, via a Merkle root; in this toy, the list is returned
    directly so folding can be inspected).
    """
    return [eval_poly(coeffs, x, prime) for x in domain]


def fold_to_constant(
    initial_evals: list[int],
    initial_domain: list[int],
    betas: list[int],
    prime: int = DEFAULT_PRIME,
) -> list[FRIFoldRound]:
    """Fold an initial evaluation vector down to a constant.

    Applies ``len(betas)`` folding rounds in sequence. The final round
    must have a domain of size 2 and an evaluations list of length 2;
    if the initial codeword is a polynomial of degree strictly less
    than ``2^(log2(N) - len(betas))``, the final folded values are
    constant across the final domain. Returns the list of intermediate
    rounds including the initial state.
    """
    n = len(initial_domain)
    if n != len(initial_evals):
        raise ValueError("initial domain and evaluations must match")
    expected_rounds = 0
    size = n
    while size > 1:
        size //= 2
        expected_rounds += 1
    if len(betas) != expected_rounds:
        raise ValueError(
            f"expected {expected_rounds} betas for domain size {n}, got {len(betas)}"
        )

    rounds: list[FRIFoldRound] = [
        FRIFoldRound(domain=list(initial_domain), evaluations=list(initial_evals), beta=0)
    ]
    evals = initial_evals
    domain = initial_domain
    for beta in betas:
        evals, domain = fold_once(evals, domain, beta, prime)
        rounds.append(FRIFoldRound(domain=domain, evaluations=evals, beta=beta))
    return rounds


def query_consistency(
    rounds: list[FRIFoldRound],
    query_index: int,
    prime: int = DEFAULT_PRIME,
) -> bool:
    """Check that consecutive fold rounds are consistent at ``query_index``.

    For each round r and its successor r+1, recompute the folded value
    at the projected index from the two evaluations at the sibling
    pair ``(L[i], L[i + |L|/2])`` of round r, and compare to the
    evaluation at the corresponding index in round r+1. Returns True
    if every consecutive pair is consistent, False otherwise.
    """
    index = query_index
    for r in range(len(rounds) - 1):
        current = rounds[r]
        nxt = rounds[r + 1]
        n = len(current.domain)
        half = n // 2
        pair_index = index % half
        x = current.domain[pair_index]
        fx = current.evaluations[pair_index]
        f_neg_x = current.evaluations[pair_index + half]
        beta = nxt.beta
        two_inv = mod_inv(2, prime)
        even = ((fx + f_neg_x) * two_inv) % prime
        odd = ((fx - f_neg_x) * two_inv) % prime
        odd = (odd * mod_inv(x, prime)) % prime
        expected = (even + beta * odd) % prime
        if expected != nxt.evaluations[pair_index]:
            return False
        index = pair_index
    return True
