"""Low-degree extension (Reed-Solomon encoding) for Chapter 34.

The trace polynomial interpolated on the trace domain is evaluated on a
larger LDE domain to produce a Reed-Solomon codeword. FRI then proves
the codeword is close to a low-degree polynomial, which is the L2
commitment to the trace polynomial under the four-layer decomposition.

The LDE domain is a coset of the order-32 subgroup of F_97^*. Choosing
a coset (rather than the subgroup itself) keeps the LDE domain disjoint
from the trace domain, which avoids zero values of the trace-domain
vanishing polynomial at LDE points. The toy uses:

- Trace domain: <64>, the order-8 subgroup (generator 64 = 28^4).
- LDE base subgroup: <28>, the order-32 subgroup.
- LDE domain: h * <28> where h = 5, the primitive root.

Because ``5`` is outside the order-32 subgroup (5 has order 96), the
coset is disjoint from the subgroup and therefore from the trace
domain. The coset is closed under negation because -1 = 28^16 is inside
the order-32 subgroup, so the coset's negation is itself.
"""

from __future__ import annotations

from .arithmetization import DEFAULT_PRIME, TRACE_DOMAIN_GENERATOR, TRACE_LENGTH


# LDE parameters over F_97.
LDE_BLOWUP = 4
LDE_SIZE = TRACE_LENGTH * LDE_BLOWUP  # 32
# 28 has order 32 in F_97* (derived from primitive root 5 via
# 5^(96/32) = 5^3 = 125 mod 97 = 28).
LDE_GENERATOR = 28
# Coset shifter. 5 is a primitive root of F_97*, so it is not in the
# order-32 subgroup generated by 28, which guarantees the coset is
# disjoint from the subgroup.
COSET_SHIFT = 5


def mod_inv(a: int, prime: int) -> int:
    """Modular inverse via Fermat's little theorem (prime modulus)."""
    if a % prime == 0:
        raise ValueError("no inverse for zero")
    return pow(a, -1, prime)


def eval_poly(coeffs: list[int], x: int, prime: int) -> int:
    """Horner-rule polynomial evaluation modulo ``prime``.

    Raises ValueError on an empty coefficient list to keep the error
    contract consistent with the rest of the package.
    """
    if not coeffs:
        raise ValueError("coefficient list must be non-empty")
    result = 0
    for c in reversed(coeffs):
        result = (result * x + c) % prime
    return result


def trace_domain(
    generator: int = TRACE_DOMAIN_GENERATOR,
    length: int = TRACE_LENGTH,
    prime: int = DEFAULT_PRIME,
) -> list[int]:
    """Return the trace domain as a list of length ``length``.

    The domain is ``{generator^i : i = 0..length-1}``. The generator
    must have order exactly ``length``. Raises ValueError if the
    generator is invalid.
    """
    if length < 2 or (length & (length - 1)) != 0:
        raise ValueError("trace length must be a power of two greater than one")
    if prime < 2:
        raise ValueError("prime must be at least two")
    domain: list[int] = []
    current = 1
    for _ in range(length):
        domain.append(current)
        current = (current * generator) % prime
    if current != 1:
        raise ValueError("generator order does not match trace length")
    return domain


def lde_domain(
    size: int = LDE_SIZE,
    generator: int = LDE_GENERATOR,
    coset_shift: int = COSET_SHIFT,
    prime: int = DEFAULT_PRIME,
) -> list[int]:
    """Return an LDE domain of size ``size`` as a coset of ``<generator>``.

    The domain is ``{coset_shift * generator^i : i = 0..size-1}``. The
    generator must have order exactly ``size``. Raises ValueError on
    non-power-of-two sizes, on an invalid generator, or on a coset
    shifter that lies inside ``<generator>`` (which would make the
    coset the subgroup itself rather than a disjoint coset).
    """
    if size < 2 or (size & (size - 1)) != 0:
        raise ValueError("size must be a power of two greater than one")
    if prime < 2:
        raise ValueError("prime must be at least two")
    if coset_shift % prime == 0:
        raise ValueError("coset_shift must be nonzero modulo prime")
    base: list[int] = []
    current = 1
    for _ in range(size):
        base.append(current)
        current = (current * generator) % prime
    if current != 1:
        raise ValueError("generator order does not match size")
    # Check that coset_shift is not in the base subgroup; if it is, the
    # coset shifter produces the same subgroup instead of a disjoint
    # coset.
    if coset_shift % prime in base:
        raise ValueError("coset_shift must lie outside the base subgroup")
    return [(coset_shift * g) % prime for g in base]


def extend_polynomial(
    coeffs: list[int],
    domain: list[int],
    prime: int = DEFAULT_PRIME,
) -> list[int]:
    """Evaluate a polynomial on ``domain`` to produce its Reed-Solomon codeword.

    Raises ValueError for an empty coefficient list or an empty domain.
    """
    if not coeffs:
        raise ValueError("coefficient list must be non-empty")
    if not domain:
        raise ValueError("domain must be non-empty")
    return [eval_poly(coeffs, x, prime) for x in domain]


def vanishing_polynomial(
    trace_pts: list[int],
    x: int,
    prime: int = DEFAULT_PRIME,
) -> int:
    """Evaluate the trace-domain vanishing polynomial at ``x``.

    Z_T(x) = prod_{w in trace_pts}(x - w) mod prime. Zero if x lies in
    trace_pts, nonzero otherwise. Raises ValueError on empty
    ``trace_pts``.
    """
    if not trace_pts:
        raise ValueError("trace_pts must be non-empty")
    product = 1
    for w in trace_pts:
        product = (product * ((x - w) % prime)) % prime
    return product
