"""Schnorr sigma protocol and Fiat-Shamir compilation for Chapter 33.

The protocol proves knowledge of a witness x in Z_n \\ {0} such that
``h = g^x mod p`` for public ``(g, h)`` in the multiplicative group
F_p^*. The same toy group Chapter 32's ``toy_kzg`` module uses is
reused here: a safe-prime ``p = 2027 = 2 * 1013 + 1`` with prime-order
subgroup ``n = 1013`` generated by ``g = 4``. Chapter 33 writes the
subgroup order ``n`` and reserves ``q`` for the adversary's query
budget, which is what ``q`` means in the sibling
``measure_and_reprogram`` module; this module follows that convention.

Three-move interactive Schnorr:

1. Prover picks nonce ``r`` uniformly in Z_n \\ {0}, sends
   ``a = g^r mod p``.
2. Verifier sends challenge ``e`` uniformly in Z_n.
3. Prover sends ``z = (r + e * x) mod n``.

Verifier accepts if ``g^z == a * h^e mod p``.

Fiat-Shamir compilation: replace the verifier's challenge with a
random oracle query at a transcript hash. The prover computes
``e = RO(pk || a)`` in place of receiving ``e`` from the verifier,
then sends the proof ``(a, z)``. The verifier recomputes the same
oracle query, derives ``e``, and runs the Schnorr verification
equation.

The classical Fiat-Shamir proof of soundness uses rewinding: extract
two accepting transcripts at the same commitment ``a`` but different
challenges, solve a 2x2 linear system in Z_n, recover x. The QROM
obstruction is that rewinding is incompatible with superposition
queries; Chapter 33's prose develops that argument, and the measure-
and-reprogram scaffolding in the sibling module illustrates the
classical side of the reduction that replaces rewinding.
"""

from __future__ import annotations

import secrets
from dataclasses import dataclass

from .rom_simulator import RandomOracle


DEFAULT_PRIME = 2027
DEFAULT_ORDER = 1013
DEFAULT_GENERATOR = 4


@dataclass
class SchnorrKeypair:
    """Schnorr witness and public key.

    ``sk`` is the witness ``x`` in ``[1, n - 1]``. ``pk`` is
    ``h = g^x mod p``. The keypair is produced by ``keygen``.
    """

    sk: int
    pk: int


@dataclass
class InteractiveTranscript:
    """Three-move interactive Schnorr transcript.

    Fields ``commitment``, ``challenge``, ``response`` correspond to
    Schnorr's ``(a, e, z)`` triple. Element ``a`` lives in F_p^*;
    ``e`` and ``z`` live in Z_n.
    """

    commitment: int
    challenge: int
    response: int


@dataclass
class FiatShamirProof:
    """Non-interactive Fiat-Shamir-compiled Schnorr proof ``(a, z)``.

    The verifier recomputes the challenge by querying the random oracle
    at the serialized transcript prefix ``pk || a``.
    """

    commitment: int
    response: int


def keygen(sk: int | None = None) -> SchnorrKeypair:
    """Generate a Schnorr keypair in the toy group.

    If ``sk`` is None, a fresh witness is sampled uniformly in
    ``[1, n - 1]`` via ``secrets.randbelow``. A deterministic ``sk``
    may be passed for reproducibility in tests.
    """
    if sk is None:
        sk = 1 + secrets.randbelow(DEFAULT_ORDER - 1)
    if sk < 1 or sk >= DEFAULT_ORDER:
        raise ValueError("sk must lie in [1, n - 1]")
    pk = pow(DEFAULT_GENERATOR, sk, DEFAULT_PRIME)
    return SchnorrKeypair(sk=sk, pk=pk)


def interactive_prove(
    keypair: SchnorrKeypair,
    challenge: int,
    nonce: int | None = None,
) -> InteractiveTranscript:
    """Run the Schnorr prover's first and third moves against a given
    challenge.

    The verifier's challenge ``e`` is passed in directly. The per-proof
    nonce ``r`` is either given (for deterministic tests) or sampled
    uniformly in ``[1, n - 1]``. Returns the full ``(a, e, z)``
    transcript.
    """
    if challenge < 0 or challenge >= DEFAULT_ORDER:
        raise ValueError("challenge must lie in [0, n - 1]")
    if nonce is None:
        nonce = 1 + secrets.randbelow(DEFAULT_ORDER - 1)
    if nonce < 1 or nonce >= DEFAULT_ORDER:
        raise ValueError("nonce must lie in [1, n - 1]")

    commitment = pow(DEFAULT_GENERATOR, nonce, DEFAULT_PRIME)
    response = (nonce + challenge * keypair.sk) % DEFAULT_ORDER
    return InteractiveTranscript(
        commitment=commitment,
        challenge=challenge,
        response=response,
    )


def interactive_verify(pk: int, transcript: InteractiveTranscript) -> bool:
    """Verify a three-move Schnorr transcript.

    Returns True iff ``g^z == a * h^e mod p``, with ``(a, e, z)``
    drawn from the transcript.
    """
    if pk < 1 or pk >= DEFAULT_PRIME:
        raise ValueError("pk must lie in [1, p - 1]")
    lhs = pow(DEFAULT_GENERATOR, transcript.response, DEFAULT_PRIME)
    rhs = (
        transcript.commitment
        * pow(pk, transcript.challenge, DEFAULT_PRIME)
    ) % DEFAULT_PRIME
    return lhs == rhs


def _transcript_bytes(pk: int, commitment: int) -> bytes:
    """Serialize ``(pk, commitment)`` for the Fiat-Shamir oracle query.

    Both elements live in ``[0, p - 1]`` so two-byte encoding suffices
    (``p = 2027 < 2^11``); we use four bytes per element for a clear
    delimiter.
    """
    if pk < 0 or pk >= DEFAULT_PRIME:
        raise ValueError("pk must lie in [0, p - 1]")
    if commitment < 0 or commitment >= DEFAULT_PRIME:
        raise ValueError("commitment must lie in [0, p - 1]")
    return pk.to_bytes(4, "big") + commitment.to_bytes(4, "big")


def fs_prove(
    keypair: SchnorrKeypair,
    oracle: RandomOracle,
    nonce: int | None = None,
) -> FiatShamirProof:
    """Produce a Fiat-Shamir-compiled Schnorr proof.

    The oracle's ``output_modulus`` must equal ``DEFAULT_ORDER`` so that
    the oracle's response lies in the Schnorr challenge space Z_n. The
    challenge ``e`` is computed as ``oracle.query(pk || a)``. The proof
    is the pair ``(a, z)``; the verifier recomputes ``e`` by querying
    the same oracle at the same serialized input.
    """
    if oracle.output_modulus != DEFAULT_ORDER:
        raise ValueError("oracle output_modulus must equal DEFAULT_ORDER")
    if nonce is None:
        nonce = 1 + secrets.randbelow(DEFAULT_ORDER - 1)
    if nonce < 1 or nonce >= DEFAULT_ORDER:
        raise ValueError("nonce must lie in [1, n - 1]")

    commitment = pow(DEFAULT_GENERATOR, nonce, DEFAULT_PRIME)
    challenge = oracle.query(_transcript_bytes(keypair.pk, commitment))
    response = (nonce + challenge * keypair.sk) % DEFAULT_ORDER
    return FiatShamirProof(commitment=commitment, response=response)


def fs_verify(pk: int, proof: FiatShamirProof, oracle: RandomOracle) -> bool:
    """Verify a Fiat-Shamir-compiled Schnorr proof against an oracle.

    Recomputes the challenge ``e = oracle.query(pk || a)`` and returns
    True iff ``g^z == a * h^e mod p``. The verifier uses the same oracle
    instance the prover queried, so subsequent verification calls hit
    the cache.
    """
    if oracle.output_modulus != DEFAULT_ORDER:
        raise ValueError("oracle output_modulus must equal DEFAULT_ORDER")
    if pk < 1 or pk >= DEFAULT_PRIME:
        raise ValueError("pk must lie in [1, p - 1]")

    challenge = oracle.query(_transcript_bytes(pk, proof.commitment))
    lhs = pow(DEFAULT_GENERATOR, proof.response, DEFAULT_PRIME)
    rhs = (proof.commitment * pow(pk, challenge, DEFAULT_PRIME)) % DEFAULT_PRIME
    return lhs == rhs


def rewind_extract(
    pk: int,
    transcript_a: InteractiveTranscript,
    transcript_b: InteractiveTranscript,
) -> int:
    """Extract the Schnorr witness from two accepting transcripts.

    Both transcripts must share the same commitment ``a`` and have
    distinct challenges ``e_a != e_b``. The witness is recovered as
    ``x = (z_a - z_b) * (e_a - e_b)^{-1} mod n``.

    This is the classical rewinding extractor. It is the step the QROM
    reduction cannot directly replicate: rewinding requires observing
    the adversary's queries at each branch, which collapses a quantum
    superposition. Measure-and-reprogram (Chapter 33 prose) is the
    replacement technique.
    """
    if transcript_a.commitment != transcript_b.commitment:
        raise ValueError("transcripts must share the same commitment")
    if transcript_a.challenge == transcript_b.challenge:
        raise ValueError("challenges must differ for extraction")
    if not interactive_verify(pk, transcript_a):
        raise ValueError("first transcript does not verify")
    if not interactive_verify(pk, transcript_b):
        raise ValueError("second transcript does not verify")

    delta_z = (transcript_a.response - transcript_b.response) % DEFAULT_ORDER
    delta_e = (transcript_a.challenge - transcript_b.challenge) % DEFAULT_ORDER
    inv_delta_e = pow(delta_e, -1, DEFAULT_ORDER)
    return (delta_z * inv_delta_e) % DEFAULT_ORDER
