"""ECDSA on a toy prime-order group, and key recovery from a reused nonce.

The chapter runs the attack in the order-11 subgroup of ``(Z/23Z)^*``
generated by ``g = 4``. Group exponentiation stands in for scalar
multiplication, and ``r`` is the group element reduced modulo the scalar
order ``N`` rather than an x-coordinate, because a multiplicative-group
element has no coordinate pair to take one from.

The recovery algebra is insensitive to how ``r`` is derived, so it is the
same on this toy as on secp256k1: ``recover_nonce`` and ``recover_key``
use only the two signatures, the two message hashes, and ``N``. Neither
touches the generator or the public key. See the package README.
"""

from __future__ import annotations

TOY_P = 23  # the ambient prime
TOY_N = 11  # the scalar order, itself prime, which is what makes inverses exist
TOY_G = 4  # a generator of the order-11 subgroup of (Z/23Z)^*


def public_key(d: int, g: int = TOY_G, p: int = TOY_P) -> int:
    """``y = g^d mod p``, the toy stand-in for the public point ``Q = dG``."""
    return pow(g, d, p)


def r_from_nonce(k: int, g: int = TOY_G, p: int = TOY_P, n: int = TOY_N) -> int:
    """``R = kG``, reduced to a scalar.

    Real ECDSA takes ``R``'s x-coordinate modulo the group order. The toy
    reduces the group element itself, which is the only difference between
    this signer and a real one.

    Not injective, in either setting. Real ECDSA always sends ``k`` and
    ``n - k`` to the same ``r``, because ``kG`` and ``-(kG)`` share an
    x-coordinate; the toy's reduction produces its own collisions, and on
    the chapter's parameters ``k = 6`` and ``k = 9`` both give ``r = 2``.
    That is why a shared ``r`` is a signal and not a proof of nonce reuse.
    """
    return pow(g, k, p) % n


def sign(z: int, d: int, k: int, r: int, n: int = TOY_N) -> int:
    """``s = k^{-1}(z + r d) mod n``.

    FIPS 186-5 rejects a signature with ``r = 0`` or ``s = 0``, and what a
    conforming signer does next depends on the nonce: a randomized one
    goes back and draws a fresh ``k``, a deterministic one outputs
    failure, because re-deriving ``k`` from the same key and message would
    reproduce the same ``r`` and ``s``. The toy raises for both, because
    its nonces are chosen by hand rather than produced either way.
    """
    if r % n == 0:
        raise ValueError("r is zero; FIPS 186-5 rejects this signature")
    s = (pow(k, -1, n) * (z + r * d)) % n
    if s == 0:
        raise ValueError("s is zero; FIPS 186-5 rejects this signature")
    return s


def verify(z: int, r: int, s: int, y: int, g: int = TOY_G, p: int = TOY_P, n: int = TOY_N) -> bool:
    """Accept iff ``(u1 G + u2 Q)`` reduces to ``r``, with ``u1 = z/s`` and ``u2 = r/s``.

    In the toy the group operation is multiplication, so the recomputed
    point is ``g^u1 y^u2 mod p``. Substituting ``s = k^{-1}(z + rd)`` sends
    that back to ``g^k``, which is where ``r`` came from.
    """
    s_inv = pow(s, -1, n)
    u1 = (z * s_inv) % n
    u2 = (r * s_inv) % n
    return (pow(g, u1, p) * pow(y, u2, p)) % p % n == r


def recover_nonce(z1: int, z2: int, s1: int, s2: int, n: int = TOY_N) -> int:
    """``k = (z1 - z2)(s1 - s2)^{-1} mod n``.

    Subtracting the two signature equations cancels the ``rd`` term, which
    is what leaves the nonce alone on one side. The inverse exists iff
    ``s1 != s2 mod n``, which for a fixed ``k`` holds iff
    ``z1 != z2 mod n``; equal hashes make ``pow(0, -1, n)`` raise, which is
    the degenerate case Exercise 2 asks about.
    """
    return ((z1 - z2) * pow(s1 - s2, -1, n)) % n


def recover_key(s1: int, k: int, z1: int, r: int, n: int = TOY_N) -> int:
    """``d = (s1 k - z1) r^{-1} mod n``.

    The first signature equation solved for ``d`` once ``k`` is known.
    """
    return ((s1 * k - z1) * pow(r, -1, n)) % n


def recover_from_two_signatures(
    z1: int, s1: int, z2: int, s2: int, r: int, n: int = TOY_N
) -> tuple[int, int]:
    """The whole attack: two signatures sharing an ``r``, out comes ``(k, d)``.

    **Assumes the two signatures really were produced under the same
    nonce.** A shared ``r`` is the signal that they might have been, not a
    proof: ``r_from_nonce`` is not injective. Given two signatures that
    share an ``r`` for some other reason, this returns a confident wrong
    answer rather than raising. Use ``recover_and_check`` when the public
    key is available, which it always is in practice.
    """
    k = recover_nonce(z1, z2, s1, s2, n)
    return k, recover_key(s1, k, z1, r, n)


def recover_and_check(
    z1: int,
    s1: int,
    z2: int,
    s2: int,
    r: int,
    y: int,
    g: int = TOY_G,
    p: int = TOY_P,
    n: int = TOY_N,
) -> tuple[int, int] | None:
    """Run the recovery, then confirm the answer against the public key.

    Returns ``(k, d)`` when the recovered key reproduces ``y``, and
    ``None`` when it does not, which is what a shared ``r`` from two
    different nonces looks like from the attacker's side. One scalar
    multiplication settles a question the algebra alone cannot.
    """
    k, d = recover_from_two_signatures(z1, s1, z2, s2, r, n)
    return (k, d) if public_key(d, g, p) == y else None
