"""ECDSA on a toy prime-order group, and key recovery from a reused nonce.

The chapter runs the attack in the order-11 subgroup of ``(Z/23Z)^*``
generated by ``g = 4``. Group exponentiation stands in for scalar
multiplication, and ``r`` is the group element reduced modulo the scalar
order ``N`` rather than an x-coordinate, because a multiplicative-group
element has no coordinate pair to take one from.

The recovery algebra is insensitive to how ``r`` is derived, so it is the
same on this toy as on secp256k1: ``recover_nonce`` and ``recover_key``
use only the two signatures, the two message hashes, and ``N``. Neither
touches the generator or the public key. See the package README.
"""

from __future__ import annotations

TOY_P = 23  # the ambient prime
TOY_N = 11  # the scalar order, itself prime, which is what makes inverses exist
TOY_G = 4  # a generator of the order-11 subgroup of (Z/23Z)^*


def public_key(d: int, g: int = TOY_G, p: int = TOY_P) -> int:
    """``y = g^d mod p``, the toy stand-in for the public point ``Q = dG``."""
    # EXERCISE: implement this function.
    #
    # Raise the generator to the private scalar modulo the ambient prime.
    # This is the toy's stand-in for the public point Q = dG.
    #
    # Reference: Chapter 6, 'Nonce reuse recovers the key'
    #
    # Proved by:
    #   tests/ch06/test_nonce_reuse.py
    raise NotImplementedError("exercise: public_key")


def r_from_nonce(k: int, g: int = TOY_G, p: int = TOY_P, n: int = TOY_N) -> int:
    """``R = kG``, reduced to a scalar.

    Real ECDSA takes ``R``'s x-coordinate modulo the group order. The toy
    reduces the group element itself, which is the only difference between
    this signer and a real one.

    Not injective, in either setting. Real ECDSA always sends ``k`` and
    ``n - k`` to the same ``r``, because ``kG`` and ``-(kG)`` share an
    x-coordinate; the toy's reduction produces its own collisions, and on
    the chapter's parameters ``k = 6`` and ``k = 9`` both give ``r = 2``.
    That is why a shared ``r`` is a signal and not a proof of nonce reuse.
    """
    # EXERCISE: implement this function.
    #
    # Raise the generator to the nonce modulo the ambient prime, then reduce
    # that group element modulo the scalar order. Real ECDSA reduces R's
    # x-coordinate instead; a multiplicative-group element has no coordinate
    # pair, and the attack does not care which rule produced r.
    #
    # Reference: Chapter 6, 'Nonce reuse recovers the key'
    #
    # Proved by:
    #   tests/ch06/test_nonce_reuse.py
    raise NotImplementedError("exercise: r_from_nonce")


def sign(z: int, d: int, k: int, r: int, n: int = TOY_N) -> int:
    """``s = k^{-1}(z + r d) mod n``.

    FIPS 186-5 rejects a signature with ``r = 0`` or ``s = 0``, and what a
    conforming signer does next depends on the nonce: a randomized one
    goes back and draws a fresh ``k``, a deterministic one outputs
    failure, because re-deriving ``k`` from the same key and message would
    reproduce the same ``r`` and ``s``. The toy raises for both, because
    its nonces are chosen by hand rather than produced either way.
    """
    # EXERCISE: implement this function.
    #
    # s = k^{-1}(z + r d) mod n, with pow(k, -1, n) for the inversion. Raise
    # ValueError before computing if r is zero modulo n, and again if the
    # computed s is zero, because FIPS 186-5 rejects a signature with
    # either. The messages are matched on 'r is zero' and 's is zero'.
    #
    # Reference: Chapter 6, 'Nonce reuse recovers the key'
    #
    # Proved by:
    #   tests/ch06/test_nonce_reuse.py
    raise NotImplementedError("exercise: sign")


def verify(z: int, r: int, s: int, y: int, g: int = TOY_G, p: int = TOY_P, n: int = TOY_N) -> bool:
    """Accept iff ``(u1 G + u2 Q)`` reduces to ``r``, with ``u1 = z/s`` and ``u2 = r/s``.

    In the toy the group operation is multiplication, so the recomputed
    point is ``g^u1 y^u2 mod p``. Substituting ``s = k^{-1}(z + rd)`` sends
    that back to ``g^k``, which is where ``r`` came from.
    """
    # EXERCISE: implement this function.
    #
    # Invert s modulo n, set u1 = z s^{-1} and u2 = r s^{-1}, recompute the
    # point as g^u1 y^u2 modulo the ambient prime, reduce it modulo n, and
    # compare against r. Chapter 4 builds this step on secp256k1;
    # substituting the signing equation collapses the recomputed point back
    # to g^k, which is where r came from.
    #
    # Reference: Chapter 4, 'Building ECDSA on secp256k1'
    #
    # Proved by:
    #   tests/ch06/test_nonce_reuse.py
    raise NotImplementedError("exercise: verify")


def recover_nonce(z1: int, z2: int, s1: int, s2: int, n: int = TOY_N) -> int:
    """``k = (z1 - z2)(s1 - s2)^{-1} mod n``.

    Subtracting the two signature equations cancels the ``rd`` term, which
    is what leaves the nonce alone on one side. The inverse exists iff
    ``s1 != s2 mod n``, which for a fixed ``k`` holds iff
    ``z1 != z2 mod n``; equal hashes make ``pow(0, -1, n)`` raise, which is
    the degenerate case Exercise 2 asks about.
    """
    # EXERCISE: implement this function.
    #
    # Subtracting the two signature equations cancels the r d term and
    # leaves s1 - s2 = k^{-1}(z1 - z2), so k = (z1 - z2)(s1 - s2)^{-1} mod
    # n. Do not special-case equal hashes: pow(0, -1, n) raising is the
    # degenerate case, and the test expects the ValueError.
    #
    # Reference: Chapter 6, 'Nonce reuse recovers the key'
    #
    # Proved by:
    #   tests/ch06/test_nonce_reuse.py
    raise NotImplementedError("exercise: recover_nonce")


def recover_key(s1: int, k: int, z1: int, r: int, n: int = TOY_N) -> int:
    """``d = (s1 k - z1) r^{-1} mod n``.

    The first signature equation solved for ``d`` once ``k`` is known.
    """
    # EXERCISE: implement this function.
    #
    # The first signature equation solved for d once k is known: d = (s1 k -
    # z1) r^{-1} mod n. Note what is absent, because the chapter makes a
    # point of it: no generator and no public key.
    #
    # Reference: Chapter 6, 'Nonce reuse recovers the key'
    #
    # Proved by:
    #   tests/ch06/test_nonce_reuse.py
    raise NotImplementedError("exercise: recover_key")


def recover_from_two_signatures(
    z1: int, s1: int, z2: int, s2: int, r: int, n: int = TOY_N
) -> tuple[int, int]:
    """The whole attack: two signatures sharing an ``r``, out comes ``(k, d)``.

    **Assumes the two signatures really were produced under the same
    nonce.** A shared ``r`` is the signal that they might have been, not a
    proof: ``r_from_nonce`` is not injective. Given two signatures that
    share an ``r`` for some other reason, this returns a confident wrong
    answer rather than raising. Use ``recover_and_check`` when the public
    key is available, which it always is in practice.
    """
    # EXERCISE: implement this function.
    #
    # Compose the two routines above: recover k from the two signatures,
    # then feed it into the key recovery, and return (k, d) in that order.
    # The shared r is an argument rather than something to derive, because
    # the attacker reads it off both signatures. Do not add a check here;
    # this function is the bare algebra and is allowed to be wrong when the
    # two nonces merely collided.
    #
    # Reference: Chapter 6, 'Nonce reuse recovers the key'
    #
    # Proved by:
    #   tests/ch06/test_nonce_reuse.py
    raise NotImplementedError("exercise: recover_from_two_signatures")


def recover_and_check(
    z1: int,
    s1: int,
    z2: int,
    s2: int,
    r: int,
    y: int,
    g: int = TOY_G,
    p: int = TOY_P,
    n: int = TOY_N,
) -> tuple[int, int] | None:
    """Run the recovery, then confirm the answer against the public key.

    Returns ``(k, d)`` when the recovered key reproduces ``y``, and
    ``None`` when it does not, which is what a shared ``r`` from two
    different nonces looks like from the attacker's side. One scalar
    multiplication settles a question the algebra alone cannot.
    """
    # EXERCISE: implement this function.
    #
    # Call recover_from_two_signatures, then recompute the public key from
    # the recovered d and compare it against the y you were given. Return
    # the (k, d) pair when they match and None when they do not. This is the
    # step that separates a real nonce reuse from two different nonces that
    # happened to produce the same r, which the algebra alone cannot tell
    # apart.
    #
    # Reference: Chapter 6, 'Nonce reuse recovers the key'
    #
    # Proved by:
    #   tests/ch06/test_nonce_reuse.py
    raise NotImplementedError("exercise: recover_and_check")
