"""The 2D lattice Chapter 3 draws, and the membership test that closes it.

Chapter 3 opens on the lattice `L` generated by `b1 = (2, 7)` and `b2 = (5, 3)`,
and *proves* that its shortest nonzero vector has norm 5 rather than merely
exhibiting one of that length. The proof is a finite enumeration, and this module
is that enumeration plus the membership test that makes it finite.

The membership test is the part worth reading. A point `(x, y)` lies in `L`
exactly when `b12 * x - b11 * y` is divisible by `abs(det B)`, which for the
chapter's basis is `7x - 2y == 0 (mod 29)`. That is derived rather than guessed.
Writing `x = a*b11 + b*b21` and `y = a*b12 + b*b22` and eliminating `a` leaves

    b12 * x - b11 * y == -b * det B

so divisibility is *necessary*. It is also *sufficient*, which is what lets the
test stand in for solving the system: `gcd(b12, b11) == 1` for this basis, so the
form is onto `Z / abs(det)`, its kernel therefore has index `abs(det)` in `Z^2`,
and `L` has that same index, so the kernel and `L` coincide. Chapter 7 develops
what a basis means over `Z`; nothing here needs more than the derivation above.

Standard library only.
"""

from __future__ import annotations

Basis = tuple[tuple[int, int], tuple[int, int]]
Point = tuple[int, int]

#: The basis Chapter 3 draws, as rows, matching the exercise's matrix B.
CHAPTER_BASIS: Basis = ((2, 7), (5, 3))


def determinant(basis: Basis) -> int:
    """The determinant of a 2x2 basis given as rows. Signed, not absolute."""
    (b11, b12), (b21, b22) = basis
    return b11 * b22 - b12 * b21


def in_lattice(basis: Basis, point: Point) -> bool:
    """Whether `point` lies in the lattice generated by `basis`.

    Uses the membership congruence derived in the module docstring, which is why
    this is a single modulo rather than a search over coefficients.
    """
    (b11, b12), _ = basis
    x, y = point
    return (b12 * x - b11 * y) % abs(determinant(basis)) == 0


def enumerate_coefficient_box(
    basis: Basis, bound: int
) -> list[tuple[int, Point, Point]]:
    """Every nonzero combination with coefficients in `[-bound, bound]`.

    Returns `(squared_norm, (a, b), (x, y))` triples sorted by squared norm, so
    the first entry is the shortest vector *inside the box*. That qualifier is
    the point of the exercise: a box search bounds the minimum from above and
    proves nothing about vectors outside it.
    """
    (b11, b12), (b21, b22) = basis
    found = []
    for a in range(-bound, bound + 1):
        for b in range(-bound, bound + 1):
            if (a, b) == (0, 0):
                continue
            x, y = a * b11 + b * b21, a * b12 + b * b22
            found.append((x * x + y * y, (a, b), (x, y)))
    found.sort()
    return found


def lattice_points_up_to(basis: Basis, max_squared_norm: int) -> list[Point]:
    """Every lattice point with squared norm at most `max_squared_norm`.

    Enumerates the integer points in the bounding square and keeps the ones the
    membership congruence accepts. The origin is included, because it is a
    lattice point; callers wanting nonzero vectors filter it out.

    This is the direction that makes the chapter's argument a proof: it is
    complete over the region, so an empty result really means no such vector
    exists rather than none was found.
    """
    limit = int(max_squared_norm**0.5)
    while (limit + 1) ** 2 <= max_squared_norm:
        limit += 1
    return [
        (x, y)
        for x in range(-limit, limit + 1)
        for y in range(-limit, limit + 1)
        if x * x + y * y <= max_squared_norm and in_lattice(basis, (x, y))
    ]


def shortest_vectors(basis: Basis) -> tuple[int, list[Point]]:
    """The squared norm of the shortest nonzero vector, and every attaining one.

    Searches outward by squared norm and stops at the first radius that contains
    a nonzero lattice point, so the answer is exact rather than a best-so-far.
    A lattice is closed under negation, so the attaining set always comes in
    plus-minus pairs and never has just one element.
    """
    radius = 1
    while True:
        points = [p for p in lattice_points_up_to(basis, radius) if p != (0, 0)]
        if points:
            best = min(x * x + y * y for x, y in points)
            return best, sorted(p for p in points if p[0] ** 2 + p[1] ** 2 == best)
        radius += 1
